# DO NOT EDIT THIS FILE
# Create a new config.py file in same dir and import, then extend this class.
import os
from telethon.tl.types import ChatBannedRights

class Config(object):
    LOGGER = True
MAX_MESSAGE_SIZE_LIMIT = 4095
